### ISSUE TITLE
problems when get the temperature from ROI

### ISSUE THREAD

**Issue by Evelyn0402** [IIT-PAVIS/AI-Thermometer#13]
Hello, 

Thank you for your code, it's really helpful!

But I don't understand when iterate the pixels value to get the temperature, why y is in range(reference_x-size_x, reference_x+size_x ),
but not y in range(reference_y-size_y, reference_y+size_y)?

Really appreciate it if someone could help me.

Evelyn

**Comment by pmorerio** [comment]
`y` is the column index in `thermal[x, y]` so it must iterate in the horizontal size of the bounding box.
