### ISSUE TITLE
What is the purpose of pose estimator?

### ISSUE THREAD

**Issue by ogencoglu** [IIT-PAVIS/AI-Thermometer#4]
Pose estimator adds unnecessary computation and slows down the inference. What is the exact purpose of that? A simple person detector would have better detection performance and would be much faster for edge devices.

**Comment by carlosbeltran** [comment]
The target is to measure head (front) temperature. The OpenPose algorithm provides sufficiently good accuracy to do so. If you think this can be achieved with a person detector please feel free to fork and contribute with such an approach. To my view, ideally, the system could be pose/detection agnostic, provided that it can accurately localize the area of interest.

**Comment by pmorerio** [comment]
The pose estimator provides precise facial landmarks for the bounding box (17,15,0,16,18) where temperature is measured. 
![image](https://user-images.githubusercontent.com/6783835/77632394-3a08aa00-6f4e-11ea-9829-08d3a5ccbe8b.png)

This is very similar to what investigated [here](https://aapm.onlinelibrary.wiley.com/doi/full/10.1118/1.1819532)

![image](https://user-images.githubusercontent.com/6783835/77635068-455dd480-6f52-11ea-8db6-2cf35ebe1026.png)

**Comment by pmorerio** [comment]
I think this can be an interesting discussion, but I am closing the issue since not a real code-related issue.
