### ISSUE TITLE
Problem when executing  ./ai_thermometer.py " syncedmem.cpp:78] Check failed: error == cudaSuccess (2 vs. 0)  out of memory *** Check failure stack trace: ***"

### ISSUE THREAD

**Issue by msedki** [IIT-PAVIS/AI-Thermometer#6]
hello,

First of all thank you very much for your share of this code in this particular situation.
Hope everything will be OK as soon as possible.
From MOROCCO TO ITALY WITH LOVE ^^

I write you because i want t use this code to secure our entry to the building, I did all the procedure to rebuild form docker how-to and the Dokerfile, everything is ok
But there's always a but :)  i got this issue with pose

<pre>root@3dc818b4ebca:/ai_thermometer# **

> ./ai_thermometer.py ./ai_thermometer.py --image_in ./samples/image1.jpeg --image_out ./results/image1_out.jpg --reference_px 200 --reference_py 400 --reference_temperature 31**

Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0331 16:20:45.623553   272 syncedmem.cpp:78] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fdff821d0cd  google::LogMessage::Fail()
    @     0x7fdff821ef33  google::LogMessage::SendToLog()
    @     0x7fdff821cc28  google::LogMessage::Flush()
    @     0x7fdff821f999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fdff72238da  caffe::SyncedMemory::gpu_data()
    @     0x7fdff707b692  caffe::Blob&lt;&gt;::gpu_data()
    @     0x7fdff7273690  caffe::CuDNNConvolutionLayer&lt;&gt;::Forward_gpu()
    @     0x7fdff71ea762  caffe::Net&lt;&gt;::ForwardFromTo()
    @     0x7fdff86594b7  op::NetCaffe::forwardPass()
    @     0x7fdff8681c92  op::PoseExtractorCaffe::forwardPass()
    @     0x7fdff867abd5  op::PoseExtractor::forwardPass()
    @     0x7fdff8677a46  op::WPoseExtractor&lt;&gt;::work()
    @     0x7fdff86b9d49  op::Worker&lt;&gt;::checkAndWork()
    @     0x7fdff86b9ed3  op::SubThread&lt;&gt;::workTWorkers()
    @     0x7fdff86c3b38  op::SubThreadQueueInOut&lt;&gt;::work()
    @     0x7fdff86bc1b1  op::Thread&lt;&gt;::threadFunction()
    @     0x7fe015fae66f  (unknown)
    @     0x7fe01c88a6db  start_thread
    @     0x7fe01cbc388f  clone
Aborted (core dumped)
</pre>

With my team we're gonna si if we can improve and then we gonna write you back 
I found searching in the web that  its related the gpu precisely the amount of memory that not fit with open Pose.. do you have more info.
how can i do to fit to my configuration below.

Spec CPU : i7 with 6 gb memory and Geforce 2gb GTX 645

Can you please help.

Best regards.
Mo'

**Comment by pmorerio** [comment]
Hi, 
looks like this is an `out of memory` problem, it is very likely that the 2GB of you GPU are not enough to run OpenPose.

**Comment by msedki** [comment]
Hi
Thank you for your reply.
Can you please tell me what is the hardware configuration  that you worked with. Thank you for directing me towards an optimal hardware configuration tu run  efficiently and without problems all this (openpose and all the 3rd party components)
thanks again

**Comment by pmorerio** [comment]
Hi. I think you need at least 8 Gb GPU RAM. But you may want to check [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) requirements.
