### ISSUE TITLE
about FLIR dataset

### ISSUE THREAD

**Issue by hkaraoguz** [IIT-PAVIS/AI-Thermometer#7]
I have downloaded the mentioned FLIR dataset. It seems the images are not radiometric calibrated. How did you choose the ambient temperature for those images during tests?

**Comment by pmorerio** [comment]
Hi,
yes images from FLIR dataset are not radiometric calibrated, they were used just to make preliminary tests to check whether OpenPose could work on such kind of images.
[As explained in the README](https://github.com/IIT-PAVIS/AI-Thermometer#without-radiometric-images) you must provide an estimate for the temperature at some pixel. We choose a point in the ground (green dot in the sample images) and provided a rough temperature estimate for it, which could be consistent with human temperature.

**Comment by hkaraoguz** [comment]
Thank you for your prompt response and detailed reply.

**Comment by Evelyn0402** [comment]
Hello, 

I'm learning about the thermal image process, could you please tell me how to do radiometric calibrated and why do that ?

Thanks in advance
Evelyn
