### ISSUE TITLE
Question : Flir camera mp4

### ISSUE THREAD

**Issue by abhatikar** [IIT-PAVIS/AI-Thermometer#9]
Is it possible to use a mp4 stream from a flir camera for processing into this code ?

**Comment by dexmac221** [comment]
yes,but actually you can use an avi file captured from a thermal camera stream (i'don't know if mp4 is a readable format, but you can make a conversion), but you need an external temperature reference point. if your stream is a sequence of radiometric images, there is no need to use external reference.
